enum QuestionCategoryEnum {
    PROJECT = 'PROJECT',
    KNOWLEDGE_AREA = 'KNOWLEDGE_AREA',
    DEPARTMENT = 'DEPARTMENT',
    DEPARTMENT_LEADER = 'DEPARTMENT_LEADER',
    RESPONSIBILITY = 'RESPONSIBILITY'
  }